apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
    spec:
      containers:
      - name: todo-db-nextjs
        image: my-image:latest
        ports:
        - containerPort: 3000
          name: todo
        env:
          - name: CLOUDANT_URL
            valueFrom:
              configMapKeyRef:
                name: todo-app-config
                key: CLOUDANT_URL
          - name: CLOUDANT_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: todo-app-config
                key: CLOUDANT_DB_NAME
          - name: CLOUDANT_APIKEY
            valueFrom:
              secretKeyRef:
                name: todo-app-secret
                key: apikey
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
