apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-config
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/rpailer/todo-app-config.git
    targetRevision: HEAD
    path: oc-kustomize/overlays/rp
  destination:
    server: https://https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace = true
    automated:
      selfHeal: true
      prune: true
